# Generated by Django 3.2 on 2022-05-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20210531_0023'),
        ('cities', '0003_alter_city_options'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from_city_set', to='cities.city', verbose_name='From which city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_city_set', to='cities.city', verbose_name='To which city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='trains',
            field=models.ManyToManyField(to='trains.Train', verbose_name='List of trains'),
        ),
    ]
