# Generated by Django 3.2 on 2021-05-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
